[2024-02-26 23:51:38,292] {/Users/raghavmaini/Desktop/rttMVP/rttDataService/utils/user.py:430} ERROR - (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
